function(set_cuda_build_properties target)
  get_target_property(_tgt_src ${target} SOURCES)
  list(FILTER _tgt_src INCLUDE REGEX "\\.cpp")

  get_target_property(_host_only_src ${target} KYNEMA_DRIVER_HOST_ONLY_CXX_SOURCES)
  if(_host_only_src)
    foreach(_src IN LISTS _host_only_src)
      get_filename_component(_src_name "${_src}" NAME)
      file(RELATIVE_PATH _src_rel "${CMAKE_SOURCE_DIR}" "${_src}")
      list(REMOVE_ITEM _tgt_src "${_src}" "${_src_rel}" "${_src_name}")
    endforeach()
    set_source_files_properties(${_host_only_src} PROPERTIES LANGUAGE CXX)
  endif()

  if(_tgt_src)
    set_source_files_properties(${_tgt_src} PROPERTIES LANGUAGE CUDA)
  endif()
  set_target_properties(${target} PROPERTIES CUDA_ARCHITECTURES "${KYNEMA_DRIVER_CUDA_ARCH}")
  set_target_properties(${target} PROPERTIES CUDA_RESOLVE_DEVICE_SYMBOLS ON)
  #set_target_properties(${target} PROPERTIES LINKER_LANGUAGE CUDA)
  if(KYNEMA_DRIVER_ENABLE_CUDA_RDC)
    set_target_properties(${target} PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
  endif()
endfunction(set_cuda_build_properties)
